name: React CI/CD

on:
  push:
    branches: [ devops_#2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install yarn
      run: | 
        yarn ci
        yarn build --if-present
    - name: Publish to Registry
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile-prod
        tags: latest
      run: |
        yarn build